title: Israel Vine
author: algae12
subtitle: null

url: "https://rahul-bothra.github.io"
baseurl: ""

# TODO: add credit
# footer_only_homepage: true
# footer_url: "https://github.com/rahul-bothra"
# footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
